site_name: '黄同学的文档仓库'
site_description: '一个存储文档的小仓库'
site_author: 'Mahoo12138'
site_url: 'https://docs.mahoo12138.cn'

repo_name: Mahoo12138/docs-with-mkdocs
repo_url: https://github.com/Mahoo12138/docs-with-mkdocs

copyright: Copyright &copy; 2019 - 2021 Mahoo12138

nav:
 - 首页: index.md
 - 学习: 
    - 冷知识 : study/knowledge.md
    - 英语文章: 
        - The blood of poor Americans: study/passages/20200229.md
        - City For The Homeless: study/passages/20200215.md
        - Floating Point Math: study/passages/20201110.md
        - Keeping it in the family: study/passages/20201124.md
    - 经验法则: study/experience.md
    - 小猪佩奇学英语: study/peppa.md
 - 文字:
    - 阅读文摘: text/digest.md
    - 动漫台词: text/anime.md
    - 音乐热评: text/netease.md
 - 我: 
    -  生活小记: 
        -  有感而发:mahoo/life.md
        -  流水账1: mahoo/diary-1.md
        -  流水账2: mahoo/diary-2.md
    -  一些想法: mahoo/thoughts.md
    - 简单道理: mahoo/truth.md
    -  我的记录: 
        - 趣测: mahoo/interesting-test.md
        - 童年回忆: mahoo/childhood.md
        - 日本动漫: mahoo/anime.md
        - 进步阶梯: mahoo/books.md
        - 开阔视野: mahoo/documentaries.md
    -  Minecraft:
        - 日志 Ⅰ: minecraft/mc-log-01.md
        - 日志 Ⅱ: minecraft/mc-log-02.md
        - 教程: minecraft/mc-tutorial.md
 - 其他:
    - Mkdocs: mkdocs/mkdocs.md
# 谷歌分析    
google_analytics:
  - UA-162023690-2
  - auto

extra_javascript : 
  - assets/js/baidu-tongji.js
  - assets/js/tables.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
# 自定义css
extra_css :
  - assets/css/ProgressBar.css

# Copyright
copyright: 'Copyright &copy; 2019-2020 Mahoo12138'

theme: 
  name: material
  icon:
    repo: fontawesome/brands/github
  font: 
    text: 'Roboto'
    code: 'Roboto Mono'
  language: zh
  logo: assets/images/logo.svg
  favicon: assets/images/logo.ico
  palette:
    primary: 'Light Blue'
    accent: 'indigo'
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.top
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mahoo12138
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mahoo12138
      name: Mahoo12138 on Twitter
    - icon: fontawesome/brands/weibo
      link: https://weibo.com/mahoo12138
    - icon: fontawesome/solid/paper-plane
      link: mailto:mahoo12138@outlook.com
      name: Email to Mahoo12138

  
 
plugins:
  - git-revision-date:
      enabled_if_env: CI
  - git-revision-date-localized:
      type: date
  - search:
      lang:
        - en
        - ja
  
      
markdown_extensions:
  - attr_list
  - footnotes
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.progressbar
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
